import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "./Providers";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sawti - Every Voice Matters",
  authors: [{ name: "Wassim Rached", url: "www.wassimrached.me" }],

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div
            style={{
              display: "flex",
              flex: 1,
              flexDirection: "column",
              minHeight: "100vh",
            }}
          >
            <Header />
            <div style={{ flex: 1, marginTop: "65px" }}>{children}</div>
          </div>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
